### PR TITLE
6 setup archi front

### LINKED ISSUE #6: Setup archi front

### PR DESCRIPTION
**Pull request by titouandeschanels**
Setup the architecture of the front of the scandelapp.

### CODE REVIEW

**Comment by titouandeschanels** [comment]
I organise the project with a page and a simple component. I move the old forward project in his own folder.

**Review by NassimAlaimi — DISMISSED** [review]
ok

**Review by EnzoBonato — APPROVED** [review]
:+1:

**Review by NassimAlaimi — APPROVED** [review]
ok

**Pull request merged**
